# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.setWindowModality(QtCore.Qt.WindowModal)
        login.resize(400, 300)
        login.setMaximumSize(QtCore.QSize(400, 300))
        login.setSizeGripEnabled(True)
        login.setModal(False)
        self.groupBox = QtWidgets.QGroupBox(login)
        self.groupBox.setGeometry(QtCore.QRect(80, 60, 241, 151))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_user = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_user.setEditable(True)
        self.comboBox_user.setCurrentText("")
        self.comboBox_user.setPlaceholderText("")
        self.comboBox_user.setObjectName("comboBox_user")
        self.gridLayout.addWidget(self.comboBox_user, 0, 1, 1, 1)
        self.pushButton_login = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_login.setObjectName("pushButton_login")
        self.gridLayout.addWidget(self.pushButton_login, 2, 1, 1, 1)
        self.label_u = QtWidgets.QLabel(self.groupBox)
        self.label_u.setObjectName("label_u")
        self.gridLayout.addWidget(self.label_u, 0, 0, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_password.setInputMask("")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setPlaceholderText("")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout.addWidget(self.lineEdit_password, 1, 1, 1, 1)
        self.label_p = QtWidgets.QLabel(self.groupBox)
        self.label_p.setObjectName("label_p")
        self.gridLayout.addWidget(self.label_p, 1, 0, 1, 1)
        self.checkBox_remeber = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_remeber.setObjectName("checkBox_remeber")
        self.gridLayout.addWidget(self.checkBox_remeber, 2, 0, 1, 1)
        self.label_log = QtWidgets.QLabel(login)
        self.label_log.setGeometry(QtCore.QRect(30, 270, 111, 16))
        self.label_log.setText("")
        self.label_log.setObjectName("label_log")
        self.layoutWidget = QtWidgets.QWidget(login)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 220, 241, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_load = QtWidgets.QLabel(self.layoutWidget)
        self.label_load.setObjectName("label_load")
        self.horizontalLayout.addWidget(self.label_load)
        self.progressBar_load = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar_load.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar_load.setProperty("value", 0)
        self.progressBar_load.setObjectName("progressBar_load")
        self.horizontalLayout.addWidget(self.progressBar_load)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "股神登录入口"))
        self.groupBox.setTitle(_translate("login", "认证"))
        self.pushButton_login.setText(_translate("login", "登录"))
        self.label_u.setText(_translate("login", "用户名"))
        self.label_p.setText(_translate("login", "密    码"))
        self.checkBox_remeber.setText(_translate("login", "记住我"))
        self.label_load.setText(_translate("login", "加载中..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QDialog()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
